on: push
name: Codechek
branches:
  - master
  - code-check
secrets:
  - name: CC_SECRET
jobs:
  codechecks:
    name: run codechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yarn
        run: |
          yarn install --frozen-lockfile
          
          npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}